In [5]:
import numpy as np

# Suggested order to complete this assignment:
** Always make sure you watch the lecture videos and read carefully the instructions under every function! 
1. <code>distances.py</code>
2. <code>k_nearest_neighbor.py</code>
3. <code>collaborative_filtering.py</code>

<code>load_movelens.py</code> is only needed for the free response questions, so the order does not really matter

# distances.py
1. Check lectures for the formulas
2. For each distance function, the inputs are a M * K np array (<code>X</code>) and a N * K np array (<code>Y</code>). The output should be a M * N array, where entry <code>[i, j]</code> is the distance between ith row of <code>X</code> and jth row of <code>Y</code>

Tip: there are many ways to implement these functions, but we strongly recommend you to use numpy methods (particularly aggregate functions) to speed up the run time. If these distance functions are not optimized, it may take a very long time to run the code needed for FR questions. 

So here are some useful functions:

In [2]:
X = np.array([1,2,3])
Y = np.array([1,4,9])

In [3]:
np.linalg.norm(X-Y, ord = None)
#Note: ord = None gives Euclidean distance. 

6.324555320336759

In [4]:
np.linalg.norm(X-Y, ord = 1)
#Note: ord = 1 gives Manhattan distance. 

8.0

In [7]:
np.sqrt([1, 4, 9, 16])

array([1., 2., 3., 4.])

In [6]:
np.dot([-1, 2, 3], [4, 5, 6])

24

In [5]:
np.square([-1, 2, 3])

array([1, 4, 9])

# k_nearest_neighbors.py
1. <code>fit</code> function: think about whether there is an actual training process for KNN models...
2. <code>predict</code> function. For each row (i.e. each data point) in the input features matrix: 
<br>
&emsp;a. find its K nearest neighbor from the training feature sets. You need use the functions implemented in distances.py: compute the distances --> sort the training data based on distances --> get the K nearest neighbors.
<br>
&emsp;b. if <code>ignore_first = True</code>, skip the closest neighbor (so you want to find K+1 nearest neighbors and get rid of the first one)
<br>
&emsp;c. use the specified aggregator to predict the class of that data point. For example, if <code>K</code> = 5 and <code>aggregator</code> = mode, the classes of 5 nearest neighbors are <code>[0,0,2,3,4]</code> --> the prediction for that data point will be 0. 
    <br>
&emsp;&emsp; - The <code>aggregator</code> decides how we aggregate/"summarize" the results from nearest neighbors into one single prediction. We want to apply the aggregator along each column/feature. 
        <br>
&emsp;&emsp; More concretely, consider 3 nearest neighbors' ratings for 4 movies: their ratings are
    <code>[ 
        &emsp;[1, 4, 2, 3],
        &emsp;[2, 4, 3, 2],
        &emsp;[1, 5, 2, 3]
    &emsp;]</code>
    <br>
    &emsp;If <code>aggregator</code> is <code>mode</code>, then we apply mode function along each column --> the result would be <code>[1, 4, 2, 3]</code>. 
    &emsp;If <code>aggregator</code> is <code>mean</code>, then we apply <code>np.mean</code> function along each column --> the result would be <code>[1.3, 4.3, 2.3, 2.7]</code>.
    &emsp;If <code>aggregator</code> is <code>median</code>, then we apply <code>np.median</code> function along each column --> the result would be <code>[1, 4, 2, 3]</code>.
&emsp;d. Do this for every row in the input <code>features</code> array
<br>
Some Tips: 
1. Note that the prediction results directly depends on the training data (meaning that we do not build a model in fit function and use that model for prediction). Therefore you need to access training data in the predict function - how do you do that? 
2. <code>mode</code> function from the statistics package may not be able to handle multiple modes in Python 3.7 (it will give you an error if the array is <code>[0,0,1,1]</code>). You could write a <code>mode</code> function yourself, using <code>np.unique</code> and <code>argmax</code> from numpy

Here are some useful functions:

In [10]:
arr = np.array([1,-2,100,3])
print(np.sort(arr, axis=0))     # sorts array
print(np.argsort(arr, axis=0))  # returns idices of sorted array

[ -2   1   3 100]
[1 0 3 2]


In [8]:
#An example for vector comprehension
nn_data = np.array([[1, 4, 2, 3],
                    [2, 4, 3, 2],
                    [1, 5, 2, 3]])
aggregator = np.median
prediction_result = [aggregator(nn_data[:, i]) for i in range(nn_data.shape[1])]
prediction_result

[1.0, 4.0, 2.0, 3.0]

# collaborative_filtering.py
Goal is to predict a person's rating by using the ratings of their K nearest neighbors
<br>
1. Essentially, we want to find K nearest neighbors for every user (i.e. every row) in the input features. Then we use the information from those K nearest neighbors to predict the ratings for a user. Note that we want to predict a user's ratings for all movies, and we only replace 0 ratings with the prediction results. 
<br>
2. In this case, we do not have an explicit target array. You will be using the same data as training features and  training targets. 
<br>
3. When you call <code>KNN.predict</code>, make sure you set <code>ignore_first</code> to be <code>True</code>. Otherwise, a data point's nearest neighbor will always be itself, which is not helpful for prediction. 
<br>

p.s.: when you answer FR questions, it is possible that after imputation, there are still a few zeros in the data. This just means that a user's nearest neighbors do not rate that movie either... But as long as your collaborative_filtering model is working correctly, a few zeros will not affect the MSEs much. 


In [9]:
x = np.array([0, 2, 3, 4, 5, 5, 4, 3, 2, 0, 0, 0])
print(np.argwhere(x == 0)) #helpful when you decide which entries you need to impute

[[ 0]
 [ 9]
 [10]
 [11]]
